name = "dewatermark"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[kv_namespaces]]
binding = "USERS_KV"
id = "8e81018e4dead3370dd15e0fa6155f16"

[vars]
NEXTAUTH_URL = "https://dewatermarkbyme.xyz"
