name = "dewatermark"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[kv_namespaces]]
binding = "USERS_KV"
id = "ece295318b65487786a6515926f1f00b"

[vars]
NEXTAUTH_URL = "https://dewatermarkbyme.xyz"
